apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-jenkins-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-jenkins-app
  template:
    metadata:
      labels:
        app: react-jenkins-app
    spec:
      containers:
        - name: react-container
          image: yourdockerhub/react-jenkins-demo:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
